### ISSUE TITLE
Suggestion: Retain original values for mapped values, dealing with int representations

### ISSUE THREAD

**Issue by daftbugs** [jollyjinx/modbus-2-mqtt-bridge#4]
Hi,

I'm currently testing if your fine tool fits my needs to interact with my PV inverter. I'm not breaking this up into individual issues but I  have 2  thoughts for now:

1.) It would be nice to (maybe optionally) have  the original value for a mapped value in the JSON as well

2.) My inverter uses individual bytes of 16 bit or 32 bit registers to represent multiple values. It also uses bitfields. I was wondering if it  would make sense to split values in the JSON representation for these cases to not have to handle dissection of these values after JSON parsing.

**Comment by jollyjinx** [comment]
Thank you for your feedback.
I've had not the need for that so I will think about it.

**Comment by jollyjinx** [comment]
Which inverter is it ? and is there documentation available on it to let me see how I could approach it.

**Comment by jollyjinx** [comment]
I'm starting a feature branch for that. It will be implemented like the *map* key in the definition dictionary  , it will be a *bitmapValues* key eg.:
```
            {
                "address": 1,
                "modbustype": "holding",
                "modbusaccess": "read",
                "valuetype": "int16",
                "mqtt": "visible",
                "interval": 10,
                "topic": "ambient/errornumber",
                "title": "Ambient Error Number",
                "bitmapValues" : {
                    "0-1": { "name" : "foo", "mqttPath" : "pathfoo" },
                    "2-5": { "name" : "bar", "mqttPath" : "pathbar" },
                    "6" :  { "name" : "baz", "mqttPath" : "pathbaz" }
                }
            }
```

**Comment by jollyjinx** [comment]
Ok the first version of the featurebranch works now. 

A Modbusvalue with ModbusValue(address: 1, value: .uint32(0b1111111))

will now be sent as:
```
{
    "address": 1,
    "bitmapValues": {
        "bar": 15,
        "baz": true,
        "foo": 3
    },
    "title": "Ambient Error Number",
    "value": 127
}```

**Comment by jollyjinx** [comment]
changed to sue *bits* instead of *bitmapValues*  in the current development branch
